apiVersion: v1
kind: Service
metadata:
  labels:
    run: nodeloadtest
  name: nodeloadtest
  namespace: default
spec:
  ports:
  - nodePort: 32069
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    run: nodeloadtest
  sessionAffinity: None
  type: LoadBalancer
