apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2017-03-28T13:17:30Z
  generation: 23
  labels:
    run: nodeloadtest
  name: nodeloadtest
  namespace: default
  resourceVersion: "1031084"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/nodeloadtest
  uid: e59eb426-13b8-11e7-ba15-42010af001cd
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nodeloadtest
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nodeloadtest
    spec:
      containers:
      - image: briangallagher/nodeloadtest:v12
        imagePullPolicy: IfNotPresent
        name: nodeloadtest
        ports:
        - containerPort: 8001
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  observedGeneration: 23
  replicas: 1
  updatedReplicas: 1
